config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "profiles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:name, :linkedin, :email, :phone, :gender)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Railsfriends" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple-v1.css">
    <link rel="stylesheet" href="https://unpkg.com/simpledotcss@2.0.0/simple-v1.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, "Name*", style: "display: block" %>
    <%= form.text_field :name, required: true %>
  </div>

  <div>
    <%= form.label :linkedin, "LinkedIn*", style: "display: block" %>
    <%= form.text_field :linkedin, required: true %>
  </div>

  <div>
    <%= form.label :email, "Email*", style: "display: block" %>
    <%= form.text_field :email, required: true %>
  </div>

  <div>
    <%= form.label :phone, "Phone*", style: "display: block" %>
    <%= form.text_field :phone, required: true %>
  </div>

  <div>
    <%= form.label :gender, "Gender*", style: "display: block" %>
    <%= form.radio_button :gender, 'boy' %> Male
    <%= form.radio_button :gender, 'girl' %> Female
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<div id="<%= dom_id profile %>">
  <p class="user-picture" style="font-size:20px; display: flex; align-items: center;">
    <i class="material-icons" style="font-size:40px; ">person</i>
  </p>
  <p>
    <span class="name-client"><%= profile.name %></span>
  </p>
  <p>
    <i class="fa fa-linkedin-square" style="font-size:24px"></i>
    <%= link_to "linkedIn/#{profile.name}", profile.linkedin  %>
  </p>

  <p>
    <i class="fa fa-envelope" style="font-size:24px"></i>
    <%= mail_to profile.email, profile.email %>
  </p>

  <p>
    <i class="fa fa-phone" style="font-size:24px"></i>
    <%= profile.phone %>
  </p>

</div>

app/views/profiles/edit.html.erb
<% content_for :title, "Editing profile" %>

<h1>Editing profile</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Show this contact", @profile %> |
  <%= link_to "Back to contacts", profiles_path %>
</div>

app/views/profiles/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Contacts" %>

<h1 style="text-align: center;">Contacts</h1>

<div id="profiles">
  <% @profiles.each do |profile| %>
    <div class="card">
      <div class="card-body">
        <%= render profile %>
        <p class="cardButton">
          <%= link_to "Show this contact", profile, class: "btn btn-primary" %>
        </p>
      </div>
    </div>
  <% end %>
</div>

<div class="new-profile-button">
  <%= link_to new_profile_path, class: "btn btn-secondary" do %>
    <i class="fa fa-plus icon"></i>
    New contact
  <% end %>
</div>

app/views/profiles/new.html.erb
<% content_for :title, "New profile" %>

<h1>New contact</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Back to contacts", profiles_path %>
</div>

app/views/profiles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @profile %>

<div>
  <%= link_to "Edit this contact", edit_profile_path(@profile) %> |
  <%= link_to "Back to contacts", profiles_path %>

  <%= button_to "Delete this contact", @profile, method: :delete%>
</div>